version: '3.6'

services:
  firewallui:
    image: firewallui
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 5000"]
    cap_add:
      - NET_ADMIN
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=app/__init__.py
      - SALT=123456789
      - SECRET_KEY=123456789      
